name: flutter_template_plus
description: flutter_template_plus

publish_to: 'none'

# 版本号
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # 本地化
  flutter_localizations:
    sdk: flutter
  # 数据持久化
  shared_preferences: ^2.0.15
  # http
  dio: ^4.0.6
  # loading 遮盖层
  flutter_easyloading: ^3.0.5
  # 状态管理
  provider: ^6.0.3
  intl: ^0.17.0
  # 路由管理
  go_router: ^4.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_ume: ^1.0.1
  flutter_ume_kit_ui: ^1.0.0
  flutter_ume_kit_device: ^1.0.0
  flutter_ume_kit_perf: ^1.0.0
  flutter_ume_kit_show_code: ^1.0.0
  flutter_ume_kit_console: ^1.0.0
  flutter_ume_kit_dio: ^1.0.0

# flutter 相关的配置选项
flutter:
  # 默认的 Material Design 字体图标
  uses-material-design: true

  # 静态资源
  assets:
    - assets/images/login/

  # 自定义字体图标（该脚手架没有用这个，用的是 Flutter 自带的默认 Icons）
  # 使用教程 https://book.flutterchina.club/chapter3/img_and_icon.html#_3-3-2-icon
  fonts:
    - family: iconfont
      fonts:
        - asset: assets/icons/iconfont.ttf

flutter_intl:
  enabled: true
